### ISSUE TITLE
Help in installling abc4pwm

### ISSUE THREAD

**Issue by sufyazi** [abc4pwm/abc4pwm#1]
Hi author(s)!

I have read your paper in BMC Bioinformatics and I am keen to test the tool described there but the README was formatted very badly for some reason and I couldn't find any guide as to how I can run the tool myself. Can I get some help with it? I assume I could just run the setup.py after cloning the repo to my local machine? 

Best,
Suffi

**Comment by Omer0191** [comment]
Hello Sufyazi!

Thank you for testing our work. We later prepared a document for installation which is clearer than current readme file. I am attaching the file here, I hope this will be easier to follow. Please let us know if there are further issues.

[Abc4pwm_docs.pdf](https://github.com/abc4pwm/abc4pwm/files/14248684/Abc4pwm_docs.pdf)

**Comment by sufyazi** [comment]
```
Installed /Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/bs4-0.0.2-py3.12.egg
Searching for sklearn
Reading https://pypi.org/simple/sklearn/
Downloading https://files.pythonhosted.org/packages/46/1c/395a83ee7b2d2ad7a05b453872053d41449564477c81dc356f720b16eac4/sklearn-0.0.post12.tar.gz#sha256=54cff9e20839b7b202321178228af4d9388bedf78425d9299fd9ee170d68802e
Best match: sklearn 0.0.post12
Processing sklearn-0.0.post12.tar.gz
Writing /var/folders/cj/48kxs2k94p7fmnmdbb42jxv00000gn/T/easy_install-8dn5e_nj/sklearn-0.0.post12/setup.cfg
Running sklearn-0.0.post12/setup.py -q bdist_egg --dist-dir /var/folders/cj/48kxs2k94p7fmnmdbb42jxv00000gn/T/easy_install-8dn5e_nj/sklearn-0.0.post12/egg-dist-tmp-sf4o_60t
error: Setup script exited with The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
rather than 'sklearn' for pip commands.

Here is how to fix this error in the main use cases:
- use 'pip install scikit-learn' rather than 'pip install sklearn'
- replace 'sklearn' by 'scikit-learn' in your pip requirements files
  (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
- if the 'sklearn' package is used by one of your dependencies,
  it would be great if you take some time to track which package uses
  'sklearn' instead of 'scikit-learn' and report it to their issue tracker
- as a last resort, set the environment variable
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
```

Hi Omer, thank you! I managed to install abc4pwm despite some pip errors (the requirements.txt in the master.zip contains abc4pwm which is not distribute on PyPI so pip got confused. Additionally I think `sklearn` in the setup.py is deprecated so I had to change it to 'scikit-learn'. 

Anyways, I think I got abc4pwm installed on my local machine, but when I tried to run the `conversion` command it says it is actually finished but there is nothing in my output folder. Do you know why is this so? My folder contains individual files in `.jaspar` format, and I want to convert them into `.mlp` format. 

My command:
```
abc4pwm conversion --pwm_files_directory /Users/sufyazi/Documents/local-storage/bioinf/repos/abc4pwm-master/data/custom_inputs/jaspar_all_motifs-D-ChIP-seq-exo-filt --in2out 'jaspar2abc4pwm' --output_folder /Users/sufyazi/Documents/local-storage/bioinf/repos/abc4pwm-master/data/outputs
```

And the returned output on the terminal was:

```
/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/bin/abc4pwm:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('abc4pwm==0.1', 'abc4pwm')

Converting from JASPAR to abc4pwm.


Conversion task finished.
```

Can you point me in the right direction? Additionally, I am unable to find more information about this "mlp" format for PWMs and I could not find its mention in your paper. Can you clarify if this is a custom format just for abc4pwm?

Sufyan

**Comment by Omer0191** [comment]
Thank you for the feedback. .mlp formate is just an extension and it was used by group for other projects. Can you please try renaming your Jasper files from .jasper to .mlp and try again? 

Please let us know for any further questions

**Comment by sufyazi** [comment]
It doesn't work. Something is unclear in terms of documentation, especially in terms of the exact compatible formats to use with the tool. Here is the error I got, and after looking deep into the module scripts, I don't think I can tweak it as the end user. 

```
abc4pwm conversion --pwm_files_directory /Users/sufyazi/Documents/local-storage/bioinf/repos/abc4pwm-master/data/custom_inputs/jaspar_all_motifs-D-ChIP-seq-exo-filt-mlp/ --in2out 'jaspar2abc4pwm' --output_folder data/outputs/
/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/bin/abc4pwm:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('abc4pwm==0.1', 'abc4pwm')

Converting from JASPAR to abc4pwm.

Traceback (most recent call last):
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/bin/abc4pwm", line 4, in <module>
    __import__('pkg_resources').run_script('abc4pwm==0.1', 'abc4pwm')
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1561, in run_script
    exec(code, namespace, namespace)
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/abc4pwm-0.1-py3.12.egg/EGG-INFO/scripts/abc4pwm", line 648, in <module>
    format_conversion.Conversion(args.pwm_files_directory,
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/abc4pwm-0.1-py3.12.egg/abc4pwm/format_conversion.py", line 44, in __init__
    self.jaspar2abc4pwm(pwm, out)
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/abc4pwm-0.1-py3.12.egg/abc4pwm/format_conversion.py", line 144, in jaspar2abc4pwm
    matrix, matrix_string, sum, max, info = read_energy_matrix_jaspar(pwm)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sufyazi/Applications/bin/micromamba/envs/abc4pwm/lib/python3.12/site-packages/abc4pwm-0.1-py3.12.egg/abc4pwm/energy_to_p.py", line 87, in read_energy_matrix_jaspar
    lss = [float(x) for x in ls]
           ^^^^^^^^
ValueError: could not convert string to float: '  33  11  25   7   2   0   0   0   0   0   0   0  15   9   7 '

```

Interesting paper and idea though, but unfortunately I don't think I can get it to work for my project. Thanks for the quick response nonetheless.

**Comment by Omer0191** [comment]
We would like to test our tool with your input data. If the data is not sensitive, please share two or three input files and I can have a look and get back to you if that's okay.

**Comment by sufyazi** [comment]
That would be nice. The PWM files I have are publicly sourced (from JASPAR database) and are in `.jaspar` format. In fact, I have them all backed up to my personal repo on my github page. You can download a few of the PWM files at the folder `jasparDB/jaspar_core_hs_nonredun_chipseq-exo-only-filt_jasp/` at this [repo](https://github.com/sufyazi/curated-ref-TF-motifs/tree/main).
